Дипломный проект - Этап 2 - 1 итерация
Toolll1/java-explore-with-me pull request #4
Opened 2023-07-12 09:49 UTC by Toolll1

2023-07-13 12:32 UTC, TomattmanYandex requested changes
комменты есть, есть что исправлять

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/controllers/CategoryController.java
> +public class CategoryController {
будет удобно тут создать еще подпакеты, по одному для каждого типа контроллера, из этих трех

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/controllers/CompilationController.java
> +public class CompilationController {
про разбиение на несколько контроллеров и валидацию параметров уже писал

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/models/category/CategoryMapper.java
> +public class CategoryMapper {
маппер это тоже не модель, под них тоже можно(нужно) отдельный пакет

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/services/CategoryService.java
> +            throw new ObjectNotFoundException("There is no category with this id");
Когда ошибки кидаешь, было бы хорошо что ни будь залогировать

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/services/CategoryService.java
> +        if (category.isEmpty()) {
у optional  есть метод orElseThrow
делает все то же самое что и строчки 89-93

2023-07-13 12:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/services/RequestService.java
> +        log.info("Received a request to create a request for params: userId {}, eventId {}", userId, eventId);
это было бы лучше логом уровня контроллера, получен запрос, это уже не уровень сервиса

2023-07-13 12:43 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/repositories/EventRepository.java
> +    List<Event> findAllByInitiatorId(int userId, PageRequest of);
о)) хз, так создалось почему-то))

2023-07-13 12:50 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/controllers/CategoryController.java
> +                                           @RequestParam(value = "size", defaultValue = "10") Integer size) {
готово

2023-07-13 14:36 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/controllers/CategoryController.java
> +public class CategoryController {
готово

2023-07-13 14:36 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/controllers/CompilationController.java
> +public class CompilationController {
готово

2023-07-13 14:41 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/models/category/CategoryDto.java
> +package ru.practicum.models.category;
готово

2023-07-13 14:42 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/repositories/EventRepository.java
> +    List<Event> findAllByInitiatorId(int userId, PageRequest of);
готово

2023-07-13 14:54 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/CategoryService.java
> +        if (category.isEmpty()) {
готово

2023-07-13 15:03 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/RequestService.java
> +        log.info("Received a request to create a request for params: userId {}, eventId {}", userId, eventId);
готово

2023-07-13 15:51 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/models/category/Category.java
> +    private final Integer id;
готово

2023-07-14 09:32 UTC, TomattmanYandex requested changes
Привет, все отлично, пакеты, стоит еще немного подогнать
второй момент, можно было бы и тесты добавить (хотя бы на самый интересный функционал)
третий момент так как это диплом и у вас есть свобода действий, можно попробовать что то новое, самое простое, библиотечка мапстракт для маппинга, поинтереснее liquibase для скриптов базы данных

Отправляю на добаботку только из-за пакетов, все остальное по желанию

2023-07-14 09:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/controllers/adminControllers/CategoryControllerAdmin.java
> +package ru.practicum.controllers.adminControllers;
по поводу имен пакетов
contollers.adminControllers
Как сказал бы учитель русскаого языка, тафталогия какая-то
внутрненний пакет по структуре понятно что относится к контроллерам, так что там можно не добавлять эту часть

2023-07-14 09:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/dto/category/CategoryDto.java
> +package ru.practicum.dto.category;
вот тут снова какое то смешение стратегий именования пакетов
сразу и по фичам и по функционалу, лучше использовать что то одно
или по фичам, т.е. пакет category и в нем все что относится к категориям, 
или по функционалу, т.е. пакет dto и там все dto без подпакетов

2023-07-14 09:32 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/models/category/Category.java
> +package ru.practicum.models.category;
снова про пакеты

2023-07-14 10:44 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/dto/category/CategoryDto.java
> +package ru.practicum.dto.category;
готово

2023-07-14 10:44 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/models/category/Category.java
> +package ru.practicum.models.category;
готово

2023-07-15 09:14 UTC, TomattmanYandex approved these changes
Принято.
по поводу большого фидбека тяжело, потому что задания типовые, но с ними справляешь отлично, замечания в основном по стилю кода, но это приходит с опытом. имена переменных, методов и тд. частенько это самая сложная часть, их придумать, но это  все с опытом приходит. а текущая программа усвоена.

2023-07-17 08:36 UTC, merged