Дипломный проект - Этап 3 - 1 итерация
Toolll1/java-explore-with-me pull request #5
Opened 2023-07-20 11:50 UTC by Toolll1

2023-07-21 09:03 UTC, TomattmanYandex requested changes
ПО структуре базы вопросики, надо решать

2023-07-21 09:03 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/models/Comment.java
> +    private List<Comment> subComments = new ArrayList<>();
все же напишу здесь
есть проблема N+1 запроса, когда есть связь один ко многим, 
ты делаешь запрос за обьектом, у которого есть список других обьектов, и спринг вметсо того чтобы подгрузить их сразу, делает запрос за основным обьектом, а потом для каждого подобьекта делает свой подзапрос
как тебе тут можно избежать этого, да и кучи другого гемороя
1) сменить методель, сделать не список подкатегорий, а одну родительскую, и подгрузку на ее поставить ленивую, так тебе при сохранении подкомента, не придётся получать родительский кммент, все его подкоменты добавлять в них новый элемент и пересохранять, просто устанговишь родительский id и все
2) когда получаешь комментарии, получить все коментарии по id события а само дерево уже обработаьь на уровне сервиса, т.е. у которых родительский id = null будут корневыми, а остальные их детскими, алгоритм сам придумывай, собирать можно сразу в dto

2023-07-21 12:30 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/controllers/admin/BanControllerAdmin.java
> +        log.info("(Admin) Received to add a user with id  {} to the ban", userId);
готово

2023-07-21 12:35 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/dto/CommentFullDto.java
> +    private final Long id;
да, ты прав) раньше у CommentFullDto было поле с EventShortDto - чтобы, когда ты написал комментарий, приходил объект, содержащий краткую информацию о нём..
но я понял, что логичнее искать событие и читать по нему комментарии
(готово)

2023-07-21 12:37 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/BanService.java
> +        return banRepository.findAll(pageable).stream().map(BanMapper::objectToDto).collect(Collectors.toList());
экономил место))
готово

2023-07-21 12:40 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/EventService.java
> +    public CommentFullDto createSubComment(CommentCreateDto dto, Long userId, Long commentId) {
обсудили в лс

2023-07-21 17:48 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/models/Comment.java
> +    private List<Comment> subComments = new ArrayList<>();
исправлено

2023-07-21 17:48 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/EventService.java
> +        banControl(userId);
исправлено

2023-07-21 17:48 UTC, Toolll1 commented on ewm-service/src/main/java/ru/practicum/services/EventService.java
> +    private Comment availabilityControl(Long commentId, Long userId, Long eventId) {
исправлено

2023-07-23 10:45 UTC, TomattmanYandex approved these changes
Принято

2023-07-23 12:51 UTC, merged